name: Benchmark

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Benchmark
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Prepare benchmarking
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
        sudo dpkg -i ./hyperfine_1.9.0_amd64.deb
        wget https://github.com/greymd/test_files/raw/master/logs/test_secure.gz
        gzip -d ./test_secure.gz
    - name: Build
      run: cargo build --release
    - name: Benchmark for each functions
      run: cargo bench
    - name: Benchmark for a large file
      run: |
        hyperfine --export-json ./read.json "./target/release/teip -r '.*sshd' < test_secure"
        hyperfine  --export-json ./convert.json './target/release/teip -c1-15 -- date -f- +%s < test_secure'
    - name: Benchmark result
      run: |
        cat ./read.json
        cat ./convert.json
